### PR TITLE
Consolidate Readme docs and Github formatting

### PR DESCRIPTION
**Pull request by twocs**
I was confused by the stale README.md document but finally found readme.txt.

This pull request removes the old file and renames the new one to the old name. It will automatically be displayed by Github on the Github page.

I also updated the formatting so it's easier to read (and shows the screenshot).

### CODE REVIEW

**Comment by cjyabraham** [comment]
Thanks for your help, however, I think we need the readme.txt as that's what the WordPress plugins directory looks for when [listing the plugin](https://wordpress.org/plugins/clone-page-tree/).  Perhaps we should just keep the txt file and remove the md file?  Would that work for github?  Any suggestions?

**Comment by dankohn** [comment]
I think you need to keep the two in sync. GitHub, I believe, needs a `.md` file for the Readme. You could create a script to generate one from the other.

**Comment by twocs** [comment]
I understand why there are two files now. GitHub will show Readme.txt if Readme.md doesn't exist (tested by searching for readme.txt files and checking the repos). The Wordpress formatting is not hard to read so I'd suggest keeping it to that new file.

Alternately the new Github actions might eventually have a script for automatically regenerating readme.md ievery time readme.txt is committed. I see plenty of parsers online.

**Comment by twocs** [comment]
You can see if you like how GitHub shows the readme.txt file on my fork
https://github.com/twocs/clone-page-tree

This pull request is now just the removal of the stale README.md.

**Comment by cjyabraham** [comment]
Looks good.  PR merged.  Thanks for looking into this @twocs .

**Pull request merged**
